services:
  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: produtos-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=${POSTGRES_ENCODING}"
      LANG: ${LANG}
      LC_ALL: ${LC_ALL}
    volumes:
      - produtos-db-data:/var/lib/postgresql/data
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    ports:
      - 5433:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rede-produtos

volumes:
  produtos-db-data:
    driver: local

networks:
  rede-produtos: