services:
  db:
    image: postgres:latest
    container_name: produtos-db
    environment:
      LANG: pt_BR.UTF-8
      LC_ALL: pt_BR.UTF-8
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=pt_BR.UTF-8
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - produtos-db-data:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - "5432:5432"
    networks:
      - rede-produtos
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: produtos-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - rede-produtos
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  produtos-db-data:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local


networks:
  rede-produtos:
    driver: bridge