services:
  - type: web
    plan: free
    name: icecream-app
    runtime: python
    repo: https://github.com/kajinmo/api.git
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0. --port 8000"
    envVars:
      - key: PORT
        value: "10000"